import os
import subprocess
import pandas as pd


def csv(molecules_dirs, output_files, aspralign_workbench_jar, aspralign_config):
    # create csv for each molecule
    for directory, output in zip(molecules_dirs, output_files):
        # run aspralign workbench and suppress output
        subprocess.run(['java', '-jar', aspralign_workbench_jar, '-f', directory, '-n', aspralign_config],
                       stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL)
        # read csv file with pandas
        dataframe = pd.read_csv(os.path.join(directory, 'ASPRAlignComparisonResults.csv'))

        # drop unnecessary columns
        dataframe.drop(dataframe.columns[1:5], axis=1, inplace=True)
        dataframe.drop(dataframe.columns[2:7], axis=1, inplace=True)
        dataframe = dataframe.iloc[:, :-1]

        # change column names
        dataframe.columns = ['Molecule 1', 'Molecule 2', 'Distance']

        # set the name of the molecules
        dataframe['Molecule 1'] = dataframe['Molecule 1'].map(lambda x: x[:-6])
        dataframe['Molecule 2'] = dataframe['Molecule 2'].map(lambda x: x[:-6])

        # save pandas dataframe to csv file
        dataframe.to_csv(output, index=False)

        # remove csv file generated by aspralign workbench
        os.remove(os.path.join(directory, 'ASPRAlignComparisonResults.csv'))
        os.remove(os.path.join(directory, 'ASPRAlignProcessedStructures.csv'))

        print(f'{output} generated')
